### ISSUE TITLE
そろばんbotの作成（旧仕様）

### ISSUE THREAD

**Issue by mochizuki-masao** [classmethod-sandbox/sparrow#10]
# 概要

Lineに送信された数値を足し算して答えるbotを作成する

# 仕様

## 有効な入力（LINE上での発言）

1. 「start」
    - ユーザーが「start」と発言すると計算モードに入る。Linebotは「calc mode start」と返す

2. 数字
    - 「start」発言以降、ユーザが数字を入力した場合はその数字をデータベースに保存する。Linebotは何も発言しない
    -  数字以外の入力があった場合はDBに保存せずLinebotは「error」と発言する。

3.「end」
    - ユーザが「end」と発言したら、直前の「start」から「end」までに入力された数字を足し合わせた数をLinebotが発言する。
    - 数字を発言した後、計算結果をリセットする
    - 次に再び「start」と入力するまでは計算を行わない

4. 「reset」
    - ユーザが「reset」と発言すると今までの計算結果をリセットする。Linebotは「reset」と返す
    - 次に再び「start」と入力するまでは計算を行わない

## 補足

- 「start」から「end」の間以外での発言には何も反応しない

**Comment by mochizuki-masao** [comment]
計算はユーザ毎に行うものとする。複数ユーザの計算を混ぜないこと

**Comment by kuni02** [comment]
仕様変更のため、本issueをクローズします。
新しいissue→#16
